name: google-auth

on:
  workflow_dispatch:

jobs:
  auth-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        token_format: access_token
        workload_identity_provider: projects/744005832574/locations/global/workloadIdentityPools/workload-identity-test/providers/github-provider-test
        service_account: workload-identity-test@pokutuna-playground.iam.gserviceaccount.com

    - name: Access secret
      run: |-
        curl https://secretmanager.googleapis.com/v1/projects/pokutuna-playground/secrets/hello/versions/latest:access \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"

    - name: Check Application Default Credential
      run: ls -l ${{ steps.auth.outputs.credentials_file_path }}
